services:
  db:
    image: postgres:15
    container_name: taste-ai-db-1
    environment:
      - POSTGRES_DB=tasteai
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: taste-ai-redis-1
    ports:
      - "6381:6379"

volumes:
  postgres_data:
