version: '3.8'

services:
  backend:
    image: taste-ai-backend:prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tasteai
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=local-production-secret-key
    depends_on:
      - db
      - redis

  frontend:
    image: taste-ai-frontend:prod
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tasteai
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_local_prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_local_prod_data:
