services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tasteai
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
