services:
  backend:
    image: taste-ai-backend:prod
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tasteai
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=no-conflicts-secret
    depends_on:
      - db
      - redis

  frontend:
    image: taste-ai-frontend:prod
    ports:
      - "3002:80"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tasteai
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
