#!/bin/bash

echo "🔍 Transforming Chris Research to Zero-Hardcoding..."

# Replace hardcoded queries with LLM-generated ones
cd ../chris_research_engine

# Transform llm_chris_queries.sh
cat > llm_chris_queries_dynamic.sh << 'SCRIPT'
#!/bin/bash

# ZERO HARDCODED QUERIES - All generated by LLMs!

generate_chris_query_categories() {
    echo "🧠 Generating Chris query categories with LLMs..."
    
    # The ONLY hardcoded prompt - asks LLMs to generate categories
    CATEGORY_META_PROMPT="Generate 50 unique categories of questions that would help deeply understand Chris Burch's psychology, investment patterns, and decision-making. Be wildly creative. Return JSON array of category names."
    
    # Generate categories with all LLMs
    ./query_chatgpt.sh "$CATEGORY_META_PROMPT" | ./store_generated_categories.sh "chatgpt" &
    ./query_claude.sh "$CATEGORY_META_PROMPT" | ./store_generated_categories.sh "claude" &
    ./query_grok.sh "$CATEGORY_META_PROMPT" | ./store_generated_categories.sh "grok" &
}

generate_prompts_for_each_category() {
    # Get all generated categories
    ALL_CATEGORIES=$(redis-cli -p 6381 -n 20 KEYS "categories:*")
    
    for category_key in $ALL_CATEGORIES; do
        CATEGORY_DATA=$(redis-cli -p 6381 -n 20 GET "$category_key")
        CATEGORIES=$(echo "$CATEGORY_DATA" | jq -r '.categories[]' 2>/dev/null)
        
        # For each category, generate 100 specific prompts
        while IFS= read -r category; do
            if [ ! -z "$category" ]; then
                PROMPT_GENERATION_REQUEST="For the category '$category', generate 100 highly specific, psychologically sophisticated prompts to analyze Chris Burch. Make them vary in approach - direct, indirect, comparative, hypothetical, scenario-based. Return as JSON array."
                
                # Generate with all LLMs
                ./query_chatgpt.sh "$PROMPT_GENERATION_REQUEST" | ./store_category_prompts.sh "$category" "chatgpt" &
                ./query_claude.sh "$PROMPT_GENERATION_REQUEST" | ./store_category_prompts.sh "$category" "claude" &
                ./query_grok.sh "$PROMPT_GENERATION_REQUEST" | ./store_category_prompts.sh "$category" "grok" &
            fi
        done <<< "$CATEGORIES"
    done
}

execute_all_generated_prompts() {
    echo "⚡ Executing ALL generated prompts..."
    
    ALL_PROMPT_SETS=$(redis-cli -p 6381 -n 20 KEYS "prompts:*")
    EXECUTION_COUNT=0
    
    for prompt_set in $ALL_PROMPT_SETS; do
        PROMPT_DATA=$(redis-cli -p 6381 -n 20 GET "$prompt_set")
        PROMPTS=$(echo "$PROMPT_DATA" | jq -r '.prompts[]?' 2>/dev/null)
        
        while IFS= read -r prompt; do
            if [ ! -z "$prompt" ]; then
                EXECUTION_COUNT=$((EXECUTION_COUNT + 1))
                
                # Execute with all LLMs
                ./query_chatgpt.sh "$prompt" | ./store_prompt_response.sh "$prompt" "chatgpt" &
                ./query_claude.sh "$prompt" | ./store_prompt_response.sh "$prompt" "claude" &
                ./query_grok.sh "$prompt" | ./store_prompt_response.sh "$prompt" "grok" &
                
                # Rate limiting
                if [ $((EXECUTION_COUNT % 100)) -eq 0 ]; then
                    wait
                    sleep 1
                fi
            fi
        done <<< "$PROMPTS"
    done
    
    echo "✅ Executed $EXECUTION_COUNT dynamically generated prompts!"
}

# Main execution loop - NO HARDCODED QUERIES!
while true; do
    generate_chris_query_categories
    sleep 30
    
    generate_prompts_for_each_category
    sleep 60
    
    execute_all_generated_prompts
    sleep 300
done
SCRIPT

chmod +x llm_chris_queries_dynamic.sh

echo "✅ Chris Research transformed to zero-hardcoding!"
